### ISSUE TITLE
language counts for missing values are not corret

### ISSUE THREAD

**Issue by JakeJing** [clld/uralic#3]
@xrotwang I noticed that the language counts for missing values are not correct in one case in UT data. For example, in UT166, there is one language (Kamas) with a missing value, but it seems that it hasn't been counted in the summary table. See link below.
https://uralic.clld.org/parameters/UT166#3/62.01/58.27

**Comment by xrotwang** [comment]
But in that case, the "missing" value is coded with the empty string - rather than `?`. Cf.
```
$ csvstat -c UT166 raw/UT/Finaldata.csv 
167. "UT166"

	Type of data:          Boolean
	Contains null values:  True (excluded from calculations)
	Unique values:         3
	Most common values:    False (17x)
	                       True (15x)
	                       None (1x)

Row count: 33
$ csvstat -c UT018 raw/UT/Finaldata.csv 
 20. "UT018"

	Type of data:          Text
	Contains null values:  False
	Unique values:         3
	Longest value:         1 characters
	Most common values:    1 (22x)
	                       0 (10x)
	                       ? (1x)

Row count: 33
```

Should both variants be interpreted in the same way?
@JakeJing can you verify?

**Comment by xrotwang** [comment]
ping @JakeJing

**Comment by JakeJing** [comment]
yes, I asked Miina to double-check this value before and she seems to forget this. I think it is ok to treat both empty and ? the same.
